---
- name: install docker build dependencies
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: yes

- name: add docker apt key
  become: yes
  apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    state: present

- name: add docker repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"

- name: install docker
  become: yes
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    update_cache: yes

- name: add {{ ansible_user }} to docker group
  become: yes
  user:
    name: "{{ ansible_user }}"
    group: docker
    append: yes

- name: get minikube binary
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /tmp/minikube-linux-amd64

- name: install minikube
  become: yes
  shell: install /tmp/minikube-linux-amd64 /usr/local/bin/minikube

- name: add minikube dependency
  become: yes
  apt:
    name:
      - conntrack

# - name: install nvidia docker
#   become: yes
#   when: nvidia_driver
#   import_tasks: nvidia_docker
