---
- name: install develop tools
  become: yes
  apt:
    name:
      - cmake
      - cmake-curses-gui
      - sqlitebrowser
      - upx
      - ccache
      - okteta
    update_cache: yes

- import_tasks: vscode.yml
- import_tasks: python.yml
- import_tasks: docker.yml
- import_tasks: rust.yml
#- import_tasks: ros2-analysis.yml

- name: install mise
  shell: curl https://mise.jdx.dev/install.sh | sh

- name: copy cyclonedds.conf for ros2
  become: yes
  copy:
    src: 60_cyclonedds.conf
    dest: /etc/sysctl.d/60_cyclonedds.conf

- name: change ifconfig permission
  become: yes
  file:
    path: /usr/sbin/ifconfig
    mode: 04755
    # why 04755 refer https://github.com/ansible/ansible/issues/13115

- name: create .ssh directory
  file:
    path: "~/.ssh"
    state: directory

- name: copy known_hosts
  file:
    src: known_hosts
    state: "~/.ssh"
