---
- name: install develop tools
  become: yes
  apt:
    name:
      - cmake
      - cmake-curses-gui
      - sqlitebrowser
    update_cache: yes

- import_tasks: vscode.yml
- import_tasks: asdf.yml
- import_tasks: python.yml
- import_tasks: docker.yml
