- name: install develop tools
  become: true
  ansible.builtin.apt:
    name:
      - cmake
      - cmake-curses-gui
      - upx
      - ccache
    update_cache: true

- import_tasks: python.yml
- import_tasks: rust.yml
# - import_tasks: ros.yml
