---
- name: install make tools
  become: yes
  apt:
    name:
      - cmake
      - cmake-curses-gui
    update_cache: yes

- import_tasks: vscode.yml
- import_tasks: asdf.yml
- import_tasks: python.yml
- import_tasks: docker.yml
