---
- name: install develop tools
  become: yes
  apt:
    name:
      - cmake
      - cmake-curses-gui
      - sqlitebrowser
      - upx
    update_cache: yes

- import_tasks: vscode.yml
- import_tasks: asdf.yml
- import_tasks: python.yml
- import_tasks: docker.yml
#- import_tasks: ros2-analysis.yml

- name: copy cyclonedds.conf for ros2
  become: yes
  copy:
    src: 60_cyclonedds.conf
    dest: /etc/sysctl.d/60_cyclonedds.conf

- name: change ifconfig permission
  become: yes
  file:
    path: /usr/sbin/ifconfig
    mode: 4755
