- name: install develop tools
  become: true
  ansible.builtin.apt:
    name:
      - cmake
      - cmake-curses-gui
      - sqlitebrowser
      - upx
      - ccache
    update_cache: true

- import_tasks: python.yml
- import_tasks: rust.yml
- import_tasks: ros.yml

- name: copy cyclonedds.conf for ros2
  become: true
  ansible.builtin.copy:
    src: 60_cyclonedds.conf
    dest: /etc/sysctl.d/60_cyclonedds.conf

- name: change ifconfig permission
  become: true
  ansible.builtin.file:
    path: /usr/sbin/ifconfig
    mode: 04755
    # why 04755 refer https://github.com/ansible/ansible/issues/13115

- name: install javascript package manage pnpm
  ansible.builtin.shell: curl -fsSL https://get.pnpm.io/install.sh | sh -

- name: install dotenvx
  ansible.builtin.shell: curl -fsS "https://dotenvx.sh?directory=$HOME/.local/bin/" | sh
