---
- name: install pip
  become: yes
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3-venv # pipx dependency
    update_cache: yes

- name: install pip packages
  ansible.builtin.pip:
    name:
      - ruff
      - pytest-repeat
      - pytest-rerunfailures
      - pytest
    executable: pip3
    extra_args: --user
