---
- name: install pip
  become: yes
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3-venv # pipx dependency
      - python3-pytest
      - python3-pytest-repeat
      - python3-pytest-rerunfailures
    update_cache: yes
