---
- name: install pip packages
  pip:
    name:
      - pre-commit
      - ruff
      - pytest-repeat
      - pytest-rerunfailures
      - pytest
      - colorcet
      - argcomplete
      - vcstool
      - kaggle
    executable: pip3
    extra_args: --user
