---
- name: install pip
  become: yes
  apt:
    name:
      - python3-pip
    update_cache: yes

- name: install pip packages
  pip:
    name:
      - ruff
      - pytest-repeat
      - pytest-rerunfailures
      - pytest
    executable: pip3
    extra_args: --user

# 冪等性担保できない
# - command: rye install pre-commit
# - command: rye install argcomplete
# - command: rye install vcstool
# - command: rye install kaggle
