---
- name: install pip
  become: yes
  apt:
    - python3-pip

- name: install pip packages
  pip:
    name:
      - ruff
      - pytest-repeat
      - pytest-rerunfailures
      - pytest
    executable: pip3
    extra_args: --user

- command: rye install pre-commit
- command: rye install argcomplete
- command: rye install vcstool
- command: rye install kaggle
