- name: download lichtblick deb
  ansible.builtin.get_url:
    url: https://github.com/Lichtblick-Suite/lichtblick/releases/download/v1.7.0/lichtblick-1.9.0-linux-amd64.deb
    dest: /tmp/lichtblick.deb

- name: Install lichtblick deb package
  become: true
  ansible.builtin.apt:
    deb: /tmp/lichtblick.deb
