---
- name: set fact
  ansible.builtin.set_fact:
    os_version: "{{ ansible_facts['distribution_version'] }}"
    ubuntu_code: "{{ ansible_facts['distribution_release'] }}"
    ansible_user: "{{ ansible_facts['user_id'] }}"
- name: Print vars
  ansible.builtin.debug:
    msg:
      - ubuntu_code: "{{ ubuntu_code }}"
      - os_version: "{{ os_version }}"
      - ansible_user: "{{ ansible_user }}"
      - ssh_port: "{{ ssh_port }}" # from env file
