---
- name: install system tools using apt
  apt:
    name:
      - cinnamon-desktop-environment
      - curl
      - dconf-editor
      - dphys-swapfile
      - gparted
      - gufw
      - hardinfo
      - linux-generic-hwe-20.04
      - meld
      - ncdu
      - terminator
      - winbind
      - zstd
    update_cache: yes
    become: yes

- name: install git latest
  apt:
    name: git
    apt_repository:
      repo: ppa:git-core/ppa
      state: present

- name: install grub-customizer
  apt:
    name: grub-customizer
    apt_repository:
      repo: ppa:danielrichter2007/grub-customizer
      state: present

- name: install fish shell
  apt:
    name: fish
    apt_repository:
      repo: ppa:fish-shell/release-3
      state: present

- name: install fisher
  shell: "curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher"

- name: set cinammon env default terminal
  dconf:
    key: "/org/cinnamon/desktop/default-applications/terminal"
    value: "['exec', 'terminator']"
    state: present

- name: set cinnamon env key custimeze (1/2)
  dconf:
    key: "/org/cinnamon/desktop/wm/preferences"
    value: "['mouse-button-modifier', \"<Super>\"]"
    state: present

- name: set cinnamon env key custimeze (2/2)
  dconf:
    key: "/org/cinnamon/desktop/wm/preferences"
    value: "['mouse-button-zoom-modifier', \"<Super>\"]"
    state: present

- name: disable sleep when close note pc dispaly
  lineinfile:
    path: /etc/systemd/logind.conf
    line: "HandleLidSwitch=ignore"
    insertafter: EOF

- name: add {{ ansible_user }} to group dialout
  user:
    name: {{ ansible_user }}
    group: dialout
    append: yes

- name: set clock local for Windows dual boot system
  timezone:
    name: Asia/Tokyo
    hwclock: local

- name: setting for winbind
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: "dns$"
    line: "dns wins"

- name: add chrome apt key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: add chrome apt repository
  apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    filename: "google-chrome"
    state: present
    update_cache: yes

- name: install google-chrome
  apt:
    name: google-chrome-stable
    state: present
