---
- name: install docker build dependencies
  become: yes
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: yes

- name: add docker apt key
  become: yes
  ansible.builtin.apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    state: present

- name: add docker repository
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ os_code }} stable"

- name: install docker
  become: yes
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    update_cache: yes

- name: add {{ ansible_user }} to docker group
  become: yes
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
