- name: update homebrew
  community.general.homebrew:
    update_homebrew: true

- name: brew install
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - 1password-cli
    - bash
    - bash-completion
    - gh
    - git
    - git-lfs
    - htop
    - ncdu
    - openssl
    - orbstack
    - tree
    - wget
    - zstd

- name: add Homebrew bash to valid shells
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: /opt/homebrew/bin/bash
    state: present
    create: true
  become: true

- name: set default shell to Homebrew bash
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /opt/homebrew/bin/bash
  become: true

- name: install homebrew cask packages
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: appdir=/Applications
  with_items:
    - 1password
    - brave-browser
    # - calibre
    - discord
    - ghostty
    - google-japanese-ime
    - microsoft-edge
    - obs
    - openvpn-connect
    - parallels-client
    - thunderbird
    - visual-studio-code
    - zen-browser

- name: install mise
  ansible.builtin.shell: curl https://mise.jdx.dev/install.sh | sh
  args:
    creates: "{{ ansible_facts['env']['HOME'] }}/.local/bin/mise"
