- name: download chrome keyring
  become: true
  ansible.builtin.shell: |
    curl -fsSL https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/google-chrome-keyring.gpg
  args:
    creates: /usr/share/keyrings/google-chrome-keyring.gpg
  when: prompt_aws != 'y' and ansible_architecture != 'aarch64'

- name: add chrome apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main
    filename: google-chrome
    state: present
  when: prompt_aws != 'y' and ansible_architecture != 'aarch64'

- name: install google-chrome
  become: true
  ansible.builtin.apt:
    name: google-chrome-stable
    update_cache: true
  when: prompt_aws != 'y' and ansible_architecture != 'aarch64'

- name: download microsoft edge keyring
  become: true
  ansible.builtin.shell: |
    curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft-edge-keyring.gpg
  args:
    creates: /usr/share/keyrings/microsoft-edge-keyring.gpg
  when: ansible_architecture != 'aarch64'

- name: add microsoft edge apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-edge-keyring.gpg] https://packages.microsoft.com/repos/edge stable main
    filename: microsoft-edge
    state: present
  when: ansible_architecture != 'aarch64'

- name: install microsoft edge
  become: true
  ansible.builtin.apt:
    name: microsoft-edge-stable
    update_cache: true
  when: ansible_architecture != 'aarch64'

- name: download brave keyring
  become: true
  ansible.builtin.get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
    mode: "0644"
  when: prompt_aws != 'y'

- name: add brave apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main
    filename: brave-browser-release
    state: present
  when: prompt_aws != 'y'

- name: install brave-browser
  become: true
  ansible.builtin.apt:
    name: brave-browser
    update_cache: true
  when: prompt_aws != 'y'

- name: install zen browser
  become: true
  community.general.flatpak:
    name: app.zen_browser.zen
    state: present
  when: prompt_aws != 'y'
