- name: set cinnamon env default terminal
  community.general.dconf:
    key: "/org/cinnamon/desktop/applications/terminal/exec" # yamllint disable-line rule:quoted-strings
    value: "'terminator'" # yamllint disable-line rule:quoted-strings
    state: present

- name: set cinnamon env key customize (1/2)
  community.general.dconf:
    key: "/org/cinnamon/desktop/wm/preferences/mouse-button-modifier" # yamllint disable-line rule:quoted-strings
    value: "'<Super>'" # yamllint disable-line rule:quoted-strings
    state: present

- name: set cinnamon env key customize (2/2)
  community.general.dconf:
    key: "/org/cinnamon/desktop/wm/preferences/mouse-button-zoom-modifier" # yamllint disable-line rule:quoted-strings
    value: "'<Super>'" # yamllint disable-line rule:quoted-strings
    state: present

- name: set start menu favorite
  community.general.dconf:
    key: "/org/cinnamon/favorite-apps" # yamllint disable-line rule:quoted-strings
    value: "['firefox.desktop', 'cinnamon-settings.desktop', 'nemo.desktop', 'terminator.desktop']" # yamllint disable-line rule:quoted-strings
    state: present

- name: disable sleep when close note pc display
  become: true
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    line: HandleLidSwitch=ignore
    insertafter: EOF
