- name: install cinnamon desktop environment
  become: true
  ansible.builtin.apt:
    name:
      - cinnamon-desktop-environment
    update_cache: true

- name: set cinnamon env key customize (1/2)
  community.general.dconf:
    key: "/org/cinnamon/desktop/wm/preferences/mouse-button-modifier" # yamllint disable-line rule:quoted-strings
    value: "'<Super>'" # yamllint disable-line rule:quoted-strings
    state: present

- name: set cinnamon env key customize (2/2)
  community.general.dconf:
    key: "/org/cinnamon/desktop/wm/preferences/mouse-button-zoom-modifier" # yamllint disable-line rule:quoted-strings
    value: "'<Super>'" # yamllint disable-line rule:quoted-strings
    state: present

