---
- name: install multimedia applications using apt
  become: yes
  ansible.builtin.apt:
    name:
      - flameshot
      - vlc
      - kolourpaint
      - obs-studio
      - libxcb-cursor0 # calibre dependency
    update_cache: yes
