---
- name: install multimedia applications using apt
  become: yes
  ansible.builtin.apt:
    name:
      - flameshot
      - vlc
      - kolourpaint
      - obs-studio
    update_cache: yes

- name: get calibre install script
  ansible.builtin.get_url:
    url: https://download.calibre-ebook.com/linux-installer.sh
    dest: /tmp/calibre-installer.sh

- name: install calibre dependency
  ansible.builtin.apt:
    name:
      - libxcb-cursor0
    update_cache: yes

- name: execute calibre install
  become: yes
  ansible.builtin.shell: bash /tmp/calibre-installer.sh
