- name: install multimedia applications using apt
  become: true
  ansible.builtin.apt:
    name:
      - flameshot
      - kolourpaint
      - libxcb-cursor0 # calibre dependency
      - obs-studio
      - vlc
    update_cache: true
sudo apt install keepassxc
