---
- name: install git latest
  become: yes
  ansible.builtin.apt:
    name: git
    update_cache: yes

- name: clone dotfiles
  git:
    repo: https://github.com/hayato-m126/dotfiles.git
    dest: ~/.dotfiles

- name: create .ssh directory
  file:
    path: "~/.ssh"
    state: directory

- name: copy known_hosts
  copy:
      src: known_hosts
      dest: ~/.ssh
