- name: install git latest
  become: true
  ansible.builtin.apt:
    name: git
    update_cache: true
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: clone dotfiles
  ansible.builtin.git:
    repo: https://github.com/hayato-m126/dotfiles.git
    dest: ~/.dotfiles

- name: create .ssh directory
  ansible.builtin.file:
    path: ~/.ssh
    state: directory

- name: copy known_hosts
  ansible.builtin.copy:
    src: known_hosts
    dest: ~/.ssh
