- name: Check if dotfiles directory exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.dotfiles"
  register: dotfiles_stat

- name: Include dotfiles role only if not exists
  ansible.builtin.include_tasks: dotfiles.yml
  when: not dotfiles_stat.stat.exists
