---
- name: add vsocode key
  become: yes
  apt_key:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    state: present

- name: add VS Code repo
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    filename: vscode
    state: present

- name: install vscode dependencies
  become: yes
  apt:
    name:
      - apt-transport-https
    state: present

- name: install VS Code
  become: yes
  apt:
    name: code
    state: present

- name: install asdf
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: ~/.asdf
    version: v0.8.0

- name: make asdf completions (1/2)
  file:
    path: ~/.config/fish/completions
    state: directory

- name: make asdf completions (2/2)
  file:
    src: ~/.asdf/completions/asdf.fish
    dest: ~/.config/fish/completions/asdf.fish
    state: link

- name: install make tools
  become: yes
  apt:
    name:
      - cmake
      - cmake-curses-gui
    update_cache: yes

- name: install pyenv build dependncies
  become: yes
  apt:
    name:
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncurses5-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libffi-dev
      - liblzma-dev
      - python-openssl
      - python3-pip
    update_cache: yes

- name: install pipx
  pip:
    name: pipx
    executable: pip3
    extra_args: --user

- name: pipx ensurepath
  shell: python3 -m pipx ensurepath

- name: pipx completion
  shell: pipx completions

- name: install argcomplete using pipx
  shell: pipx install argcomplete

- name: get poetry install.py
  get_url:
    url: https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py
    dest: /tmp/install-poetry.py

- name: install poetry to default python3
  shell: python3 /tmp/install-poetry.py

- name: install docker build dependncies
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: yes

- name: add docker apt key
  become: yes
  apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    state: present

- name: add docker repositry
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"

- name: install docker
  become: yes
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    update_cache: yes

# - name: add use to docker group
#   become: yes
#   user:
#     name: hyt
#     group: docker
#     append: yes

