- name: copy font conf
  become: true
  ansible.builtin.copy:
    src: local.conf
    dest: /etc/fonts/local.conf

- name: Ensure a locale exists
  become: true
  community.general.locale_gen:
    name: ja_JP.UTF-8
    state: present

- name: keyboard setting
  become: true
  ansible.builtin.command: localectl set-x11-keymap jp jp106

- name: change locale
  become: true
  ansible.builtin.command: update-locale LANG=ja_JP.UTF-8

- name: install input method
  become: true
  ansible.builtin.apt:
    name:
      - fcitx-mozc
      - x11-xserver-utils
    update_cache: true

- name: input method setting
  ansible.builtin.blockinfile:
    path: ~/.profile
    block: |
      export GTK_IM_MODULE=fcitx
      export QT_IM_MODULE=fcitx
      export XMODIFIERS=@im=fcitx
      export DefaultIMModule=fcitx
      if [ $SHLVL = 1 ] ; then
          fcitx-autostart > /dev/null 2>&1
          xset -r 49
      fi

- name: unzip
  become: true
  ansible.builtin.apt:
    name:
      - unzip
    update_cache: true
