---
- name: Add Ubuntu Japanese PPA keyring
  ansible.builtin.apt_key:
    url: https://www.ubuntulinux.jp/ubuntu-jp-ppa-keyring.gpg
    state: present

- name: Add Ubuntu Japanese archive keyring
  ansible.builtin.apt_key:
    url: https://www.ubuntulinux.jp/ubuntu-ja-archive-keyring.gpg
    state: present

- name: Download Ubuntu Japanese repository
  ansible.builtin.get_url:
    url: https://www.ubuntulinux.jp/sources.list.d/jammy.list
    dest: /etc/apt/sources.list.d/ubuntu-ja.list

- name: install ja package
  apt:
    name:
      - ubuntu-defaults-ja
      - language-pack-ja
    update_cache: yes

- name: copy font conf
  copy:
    src: local.conf
    dest: /etc/fonts/local.conf

- name: Ensure a locale exists
  community.general.locale_gen:
    name: ja_JP.UTF-8
    state: present

- name: keyboard setting
  command: localectl set-x11-keymap jp jp106

- name: change locale
  command: update-locale LANG=ja_JP.UTF-8

- name: install input method
  apt:
    name:
      - fcitx-mozc
      - x11-xserver-utils
    update_cache: yes

- name: input method setting
  become: no
  blockinfile:
    path: ~/.profile
    block: |
      export GTK_IM_MODULE=fcitx
      export QT_IM_MODULE=fcitx
      export XMODIFIERS=@im=fcitx
      export DefaultIMModule=fcitx
      if [ $SHLVL = 1 ] ; then
          fcitx-autostart > /dev/null 2>&1
          xset -r 49
      fi

- name: unzip
  apt:
    name:
      - unzip
    update_cache: yes