- name: copy font conf
  become: true
  ansible.builtin.copy:
    src: local.conf
    dest: /etc/fonts/local.conf

- name: Ensure a locale exists
  become: true
  community.general.locale_gen:
    name: ja_JP.UTF-8
    state: present

- name: install software
  become: true
  ansible.builtin.apt:
    name:
      - x11-xkb-utils
      - unzip
      - wslu
    update_cache: true

- name: change locale
  become: true
  ansible.builtin.command: update-locale LANG=ja_JP.UTF-8

- name: install input method
  become: true
  ansible.builtin.apt:
    name:
      - fcitx5-mozc
      # - x11-xserver-utils
    update_cache: true

- name: input method setting
  ansible.builtin.blockinfile:
    path: ~/.profile
    block: |
      setxkbmap -layout jp
      export GTK_IM_MODULE=fcitx5
      export QT_IM_MODULE=fcitx5
      export XMODIFIERS=@im=fcitx5
      export DefaultIMModule=fcitx5
      export INPUT_METHOD=fcitx5
      if [ $SHLVL = 1 ] ; then
          (fcitx5 --disable=wayland -d --verbose '*'=0 &)
      fi
