- name: copy font conf
  become: true
  ansible.builtin.copy:
    src: local.conf
    dest: /etc/fonts/local.conf

- name: Ensure a locale exists
  become: true
  community.general.locale_gen:
    name: ja_JP.UTF-8
    state: present

- name: change locale
  become: true
  ansible.builtin.command: update-locale LANG=ja_JP.UTF-8
