- name: setup local machine
  hosts: localhost
  connection: local
  vars_prompt:
    - name: prompt_wsl
      prompt: Is target environment WSL? [y/N]
      private: false
    - name: prompt_hyper_v
      prompt: Is target environment Hyper-V? [y/N]
      private: false
    - name: prompt_desktop
      prompt: Is target environment is desktop(GUI)? [y/N]
      private: false
    - name: prompt_container
      prompt: Set up Container Environment? [y/N]
      private: false
    - name: prompt_remote
      prompt: Set up remote tools? [y/N]
      private: false
    - name: prompt_robotics
      prompt: Set up robotics development tools? [y/N]
      private: false
  roles:
    - role: japanese
    - role: wsl
      when: prompt_wsl == 'y'
    - role: dotfiles
    - role: system
    - role: desktop
      when: prompt_desktop == 'y'
    - role: hyper_v
      when: prompt_hyper_v == 'y'
    - role: container
      when: prompt_container == 'y'
    - role: remote
      when: prompt_remote == 'y'
    - role: dora
      when: prompt_robotics == 'y'
    # - role: ros
    #   when: prompt_robotics == 'y'
