---
- name: install multimedia applications using apt
  become: yes
  apt:
    name:
      - flameshot
      - vlc
      - kolourpaint
      - obs-studio
    update_cache: yes

- name: get calibre install script
  get_url:
    url: https://download.calibre-ebook.com/linux-installer.sh
    dest: /tmp/calibre-installer.sh

- name: execute calibre install
  become: yes
  shell: bash /tmp/calibre-installer.sh
